import type { Database, Task, AgentEvent } from '../types';
const base = '2026-09-08T06:';
const tasks: Task[] = [
  [
    'tsk-1048',
    'Inspection Report Analysis',
    'document',
    'completed',
    7,
    '24:00',
    'doc-01',
  ],
  ['tsk-1047', 'Pipeline Calculation', 'code', 'completed', 7, '18:00', ''],
  [
    'tsk-1046',
    'Vendor Document Review',
    'document',
    'running',
    2,
    '27:00',
    'doc-04',
  ],
  ['tsk-1045', 'SOP Comparison', 'document', 'queued', -1, '28:00', 'doc-02'],
  ['tsk-1044', 'Pressure Drop Calculation', 'code', 'failed', 4, '10:00', ''],
].map(
  ([id, title, type, status, step, time, doc]) =>
    ({
      id,
      title,
      type,
      status,
      step,
      started: base + time + 'Z',
      duration: status === 'completed' ? 42 : 0,
      prompt:
        type === 'code'
          ? 'Calculate pressure drop for a 120 m pipeline, internal diameter 0.15 m, flow 0.025 m³/s, density 998 kg/m³ and Darcy friction factor 0.02. Include unit tests.'
          : 'Review the attached industrial inspection report. Summarize findings, identify missing information, and prepare a draft approval note with source references.',
      ownerId: 'usr-01',
      documentIds: doc ? [doc] : [],
      events: [],
      modelId: type === 'code' ? 'master-1' : 'vision-1',
      nodeId: 'node-01',
      tokens: status === 'completed' ? 2840 : 0,
      scenario: status === 'failed' ? 'sandbox_failure' : 'normal',
      ...(status === 'failed'
        ? {
            error:
              'Synthetic test failure: missing positive-diameter validation. Exit code 1. Sandbox stopped.',
          }
        : {}),
    }) as Task,
);
const historical: AgentEvent[] = [
  'task_received',
  'task_classified',
  'model_routed',
  'ocr_completed',
  'rag_search',
  'agent_reasoning',
  'document_generated',
  'task_completed',
].map((type, i) => ({
  id: 'evt-seed-' + i,
  taskId: 'tsk-1048',
  type,
  step: type,
  status: 'completed',
  message: type.replaceAll('_', ' '),
  timestamp: `2026-09-08T06:24:${String(i * 5).padStart(2, '0')}Z`,
  model: 'Qwen 2.5 - VL (7B or 30B)',
}));
tasks[0].events = historical;
tasks[1].events = historical.map((e) => ({
  ...e,
  id: e.id + 'c',
  taskId: 'tsk-1047',
}));
export function createSeed(): Database {
  return structuredClone({
    orchestrator: {
      model: 'Demo 2B orchestrator',
      nodeId: 'control-plane',
      configured: true,
      endpointHost: 'localhost',
      role: 'Intent classification and workflow planning',
    },
    users: [
      {
        id: 'usr-01',
        name: 'Operator 01',
        email: 'operator@omnitrix.local',
        role: 'user',
        department: 'Engineering',
        permissions: ['documents', 'knowledge', 'code', 'tasks', 'audit'],
        modelAccess: ['MASTER', 'VISION', 'FAST', 'LIBRARIAN'],
        dailyLimit: 50000,
        monthlyLimit: 1000000,
        used: 32410,
        monthlyUsed: 482600,
        enabled: true,
        lastActivity: base + '28:00Z',
      },
      {
        id: 'usr-admin',
        name: 'Administrator',
        email: 'admin@omnitrix.local',
        role: 'admin',
        department: 'IT & Infrastructure',
        permissions: [
          'admin',
          'documents',
          'knowledge',
          'code',
          'tasks',
          'audit',
        ],
        modelAccess: ['MASTER', 'VISION', 'FAST', 'LIBRARIAN'],
        dailyLimit: 200000,
        monthlyLimit: 5000000,
        used: 18420,
        monthlyUsed: 681100,
        enabled: true,
        lastActivity: base + '22:00Z',
      },
      {
        id: 'usr-02',
        name: 'Ananya Rao',
        email: 'ananya@omnitrix.local',
        role: 'user',
        department: 'Operations',
        permissions: ['documents', 'knowledge', 'tasks', 'audit'],
        modelAccess: ['MASTER', 'VISION', 'FAST', 'LIBRARIAN'],
        dailyLimit: 40000,
        monthlyLimit: 800000,
        used: 12600,
        monthlyUsed: 210000,
        enabled: true,
        lastActivity: base + '14:00Z',
      },
      {
        id: 'usr-03',
        name: 'Vikram Mehta',
        email: 'vikram@omnitrix.local',
        role: 'user',
        department: 'Quality Assurance',
        permissions: ['documents', 'knowledge', 'tasks', 'audit'],
        modelAccess: ['VISION', 'FAST', 'LIBRARIAN', 'MASTER'],
        dailyLimit: 30000,
        monthlyLimit: 600000,
        used: 8800,
        monthlyUsed: 184000,
        enabled: false,
        lastActivity: '2026-09-07T09:20:00Z',
      },
    ],
    models: [
      {
        id: 'master-1',
        name: 'LLAMA 3-70B Instruct',
        group: 'MASTER',
        role: 'Complex reasoning & planning',
        enabled: true,
        priority: 1,
        nodeId: 'node-02',
        context: 32768,
      },
      {
        id: 'master-2',
        name: 'Qwen 2.5 -32B',
        group: 'MASTER',
        role: 'Reasoning fallback',
        enabled: true,
        priority: 2,
        nodeId: 'node-01',
        context: 32768,
      },
      {
        id: 'vision-1',
        name: 'Qwen 2.5 - VL (7B or 30B)',
        group: 'VISION',
        role: 'Document vision & OCR',
        enabled: true,
        priority: 1,
        nodeId: 'node-01',
        context: 32768,
      },
      {
        id: 'vision-2',
        name: 'LLAMA 3.2 - Vision (11B)',
        group: 'VISION',
        role: 'Visual understanding fallback',
        enabled: true,
        priority: 2,
        nodeId: 'node-02',
        context: 16384,
      },
      {
        id: 'fast-1',
        name: 'LLAMA3 (8B Intruct)',
        group: 'FAST',
        role: 'Fast text & summaries',
        enabled: true,
        priority: 1,
        nodeId: 'node-01',
        context: 8192,
      },
      {
        id: 'fast-2',
        name: 'Gema 2 (9B)',
        group: 'FAST',
        role: 'Text generation fallback',
        enabled: true,
        priority: 2,
        nodeId: 'node-02',
        context: 8192,
      },
      {
        id: 'lib-1',
        name: 'Nominic Embed text',
        group: 'LIBRARIAN',
        role: 'Local document embeddings',
        enabled: true,
        priority: 1,
        nodeId: 'node-02',
        context: 8192,
      },
      {
        id: 'lib-2',
        name: 'BAAI/bge-M3',
        group: 'LIBRARIAN',
        role: 'Multilingual retrieval',
        enabled: true,
        priority: 2,
        nodeId: 'node-03',
        context: 8192,
      },
    ],
    nodes: [
      {
        id: 'node-01',
        name: 'NODE 01',
        host: '10.0.0.11',
        type: 'INFERENCE SERVER',
        accelerator: 'Local accelerator',
        memory: 128,
        status: 'online',
        capacity: 8,
        utilization: 64,
        activeTasks: 2,
      },
      {
        id: 'node-02',
        name: 'NODE 02',
        host: '10.0.0.12',
        type: 'COMPUTE NODE',
        accelerator: 'Local accelerator',
        memory: 256,
        status: 'online',
        capacity: 12,
        utilization: 42,
        activeTasks: 1,
      },
      {
        id: 'node-03',
        name: 'NODE 03',
        host: '10.0.0.13',
        type: 'PRIVATE CLUSTER',
        accelerator: 'Mixed compute',
        memory: 512,
        status: 'degraded',
        capacity: 16,
        utilization: 82,
        activeTasks: 3,
      },
    ],
    routing: [
      {
        id: 'route-master',
        task: 'Document reasoning',
        group: 'MASTER',
        primaryId: 'master-1',
        fallbackId: 'master-2',
        strategy: 'least_loaded',
      },
      {
        id: 'route-vision',
        task: 'Vision / OCR',
        group: 'VISION',
        primaryId: 'vision-1',
        fallbackId: 'vision-2',
        strategy: 'least_loaded',
      },
      {
        id: 'route-fast',
        task: 'Fast text / summaries',
        group: 'FAST',
        primaryId: 'fast-1',
        fallbackId: 'fast-2',
        strategy: 'priority',
      },
      {
        id: 'route-lib',
        task: 'Knowledge retrieval',
        group: 'LIBRARIAN',
        primaryId: 'lib-1',
        fallbackId: 'lib-2',
        strategy: 'least_loaded',
      },
    ],
    documents: [
      ['doc-01', 'Inspection Report.pdf', 12, 84],
      ['doc-02', 'Pipeline Safety SOP.pdf', 24, 156],
      ['doc-03', 'Maintenance Manual.pdf', 48, 312],
      ['doc-04', 'Vendor Specification.pdf', 18, 128],
    ].map(([id, name, pages, chunks]) => ({
      id,
      name,
      pages,
      chunks,
      type: 'PDF',
      size: 2400000,
      status: 'indexed',
      updated: '2026-09-08',
      ownerId: 'usr-01',
      source: 'sample',
      knowledge: true,
    })),
    tasks,
    audit: [
      ...historical
        .slice()
        .reverse()
        .map((e, i) => ({
          id: 'aud-' + i,
          timestamp: e.timestamp,
          actorId: 'usr-01',
          actor: 'Operator 01',
          action: e.type.toUpperCase(),
          resource: 'Inspection Report Analysis',
          taskId: e.taskId,
          status: 'success',
        })),
      {
        id: 'aud-admin-1',
        timestamp: base + '20:00Z',
        actorId: 'usr-admin',
        actor: 'Administrator',
        action: 'MODEL_ENABLED',
        resource: 'LLAMA 3-70B Instruct',
        status: 'success',
      },
      {
        id: 'aud-admin-2',
        timestamp: base + '15:00Z',
        actorId: 'usr-admin',
        actor: 'Administrator',
        action: 'TOKEN_LIMIT_CHANGED',
        resource: 'Operator 01 / 50,000 daily',
        status: 'success',
      },
    ],
    settings: {
      organization: 'Industrial Operations Division',
      dailyLimit: 500000,
      monthlyLimit: 12000000,
      retentionDays: 365,
      timeout: 120,
      offline: false,
      departmentLimits: {
        Engineering: 150000,
        Operations: 120000,
        'Quality Assurance': 80000,
        'IT & Infrastructure': 150000,
      },
      requireReview: true,
    },
    localRequests: 17,
  } as Database);
}
