import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Download, Copy, FileText } from 'lucide-react';
import { useApp } from '../state/AppContext';
import {
  Button,
  PageHeader,
  Empty,
  StatusBadge,
  ErrorMessage,
  SectionHeading,
} from './common';
import DocumentViewer from './DocumentViewer';
import AgentTimeline from './AgentTimeline';
import { downloadBlob, exportReport, exportSupplement } from '../api/exports';
import { documentApi } from '../api/documents';
import type { LocalDocument } from '../types';

function DocumentStatus({ document }: { document: LocalDocument }) {
  const { act } = useApp();
  const [busy, setBusy] = useState(false);
  return (
    <div className="panel">
      <div className="inline-actions">
        <StatusBadge status={document.status} />
        {document.status === 'failed' && (
          <Button
            loading={busy}
            onClick={async () => {
              setBusy(true);
              try {
                await act(
                  () => documentApi.reindex(document.id),
                  'Indexing queued',
                );
              } finally {
                setBusy(false);
              }
            }}
          >
            Retry indexing
          </Button>
        )}
      </div>
      {document.error && <ErrorMessage message={document.error} />}
      {document.status === 'processing' && (
        <p className="note">
          Preparing this document for local search. Its status updates
          automatically.
        </p>
      )}
    </div>
  );
}

export default function LiveTaskResult() {
  const { id } = useParams();
  const { data, act } = useApp();
  const [format, setFormat] = useState('');
  const task =
    data?.tasks.find((t) => t.id === id) ||
    data?.tasks.find((t) => t.documentIds.includes(id ?? ''));
  const source =
    data?.documents.find((d) => d.id === id) ||
    data?.documents.find((d) => task?.documentIds.includes(d.id));
  if (!task)
    return source ? (
      <>
        <PageHeader title={source.name} eyebrow="LOCAL DOCUMENT" />
        <DocumentStatus document={source} />
        <DocumentViewer document={source} />
      </>
    ) : (
      <Empty message="This result is unavailable." />
    );
  const documents =
    data?.documents.filter((d) => task.documentIds.includes(d.id)) ?? [];
  async function download(next: 'pdf' | 'docx' | 'xlsx' | 'pptx') {
    setFormat(next);
    await act(
      () =>
        next === 'pdf' || next === 'docx'
          ? exportReport(task!, documents, next)
          : exportSupplement(task!, next),
      'Output downloaded',
    );
    setFormat('');
  }
  return (
    <>
      <Link
        className="breadcrumb-back"
        to={`/workspace/chats/${task.conversationId ?? task.id}`}
      >
        <ArrowLeft size={13} />
        Back to conversation
      </Link>
      <PageHeader
        title={task.title}
        eyebrow={task.type === 'code' ? 'CODE & REASONING' : 'DOCUMENT REVIEW'}
        description="Generated by your configured local inference services."
        action={<StatusBadge status={task.status} />}
      />
      {task.error && <ErrorMessage message={task.error} />}
      <div className="live-result-layout">
        <section className="panel">
          <SectionHeading label="RESPONSE" />
          <div className="chat-answer-text">
            {task.reply ? (
              <p>{task.reply}</p>
            ) : (
              <p>
                Your response will appear here as the worker processes the
                request.
              </p>
            )}
          </div>
          {task.status === 'completed' && (
            <div className="inline-actions">
              {(['docx', 'pdf', 'xlsx', 'pptx'] as const).map((next) => (
                <Button
                  key={next}
                  loading={format === next}
                  onClick={() => void download(next)}
                >
                  <Download size={14} />
                  {next.toUpperCase()}
                </Button>
              ))}
            </div>
          )}
          {task.type === 'code' && task.code && (
            <div className="live-code-output">
              <div className="section-heading">
                <span className="eyebrow">GENERATED SOURCE</span>
                <div className="inline-actions">
                  <Button
                    onClick={() =>
                      void act(
                        () => navigator.clipboard.writeText(task.code!),
                        'Code copied',
                      )
                    }
                  >
                    <Copy size={14} />
                    Copy
                  </Button>
                  <Button
                    onClick={() =>
                      downloadBlob(
                        new Blob([task.code!], { type: 'text/plain' }),
                        'generated.py',
                      )
                    }
                  >
                    <Download size={14} />
                    Download
                  </Button>
                </div>
              </div>
              <pre>{task.code}</pre>
              <p className="note">
                Code has not been executed. Review and test it in your approved
                execution environment.
              </p>
            </div>
          )}
          <p className="note">
            Draft output · verify source references and review before
            operational use.
          </p>
        </section>
        <aside className="panel">
          <SectionHeading label="EXECUTION RECORD" />
          <AgentTimeline task={task} />
          <SectionHeading label="SOURCE REFERENCES" />
          {task.citations?.length ? (
            task.citations.map((c, i) => (
              <div
                className="context-item"
                key={`${c.documentId}-${c.page}-${i}`}
              >
                <Link to={`/workspace/documents/${c.documentId}`}>
                  <FileText size={13} />
                  {c.name} · page {c.page}
                </Link>
                <p>{c.excerpt}</p>
              </div>
            ))
          ) : (
            <p className="note">No source references were returned.</p>
          )}
        </aside>
      </div>
      {source && (
        <div className="standalone-document">
          <SectionHeading label="ORIGINAL DOCUMENT" />
          <DocumentStatus document={source} />
          <DocumentViewer document={source} />
        </div>
      )}
    </>
  );
}
